/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.6.1/samples
 */
plugins {
    id("org.asciidoctor.jvm.convert") version "3.3.2"
}

repositories {
        mavenCentral()
}

tasks {
    "asciidoctor"(org.asciidoctor.gradle.jvm.AsciidoctorTask::class) {
        sourceDir(".")
        baseDirIsProjectDir()
        resources(delegateClosureOf<CopySpec> {
            from("images") {
                include("**/*.jpeg")
                include("**/*.png")
                include("**/*.svg")
                into("img")
            }
        })
    }
}

asciidoctorj {
    modules {
        diagram.use()
        diagram.setVersion("1.5.16")
    }
}
