name: Build and Deploy AsciiDoc to GitHub Pages

on:
  push:
    branches:
      - main # Replace with the branch where you have your code and gradle files

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    # Cache dependencies for faster build
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Build AsciiDoc to HTML using Gradle
      run: ./gradlew asciidoctor

    # Assuming the HTML files are generated inside `build/asciidoc/html5/` directory
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        publish_dir: ./build/docs/asciidoc/ # Replace with the path where HTML files are generated
        keep_files: true
        publish_branch: gh-pages # Branch to deploy the generated HTML files to
